### ISSUE TITLE
Harvest sources set to private automatically

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#897]
Occasionally, making changes through admin UI for catalog for a harvest source will set the setting to private instead of public.

## How to reproduce

1. Haven't been able to reproduce, but occurred with setting up recent Pennsylvania geospatial source.

## Expected behavior

If a harvest source was already set at public, making a change to the source through the UI should not change the source from public to private.

## Actual behavior

Occasionally the harvest source has been changed to private on dataset visibility, for unknown reasons, and if unnoticed the datasets will be private after you save your changes through the UI.
![Screen Shot 2019-08-19 at 4 36 35 PM](https://user-images.githubusercontent.com/3236989/63297846-51890180-c2a0-11e9-9491-95fd52c8ecce.png)

**Comment by mogul** [comment]
[Fuhu said](https://github.com/GSA/datagov-deploy/issues/2085#issuecomment-681981600): 
> It affects UI only. Datasets harvested uses the correct Dataset Visibility when the source page is saved. But if the user edit the source page and save it again without noticing the Dataset Visibility is changed to private by this UI bug, all new datasets will be harvested as private.

**Comment by mogul** [comment]
This is another one that may be fixed by ckan-next, but we should look into it in the near term to avoid accidents.

**Comment by avdata99** [comment]
Moving this to QA since we can't reproduce. It seems fixed with previous changes.

**Comment by pjsharpe07** [comment]
Not sure if we want to change this, but for catalog-classic the issue comes from [this line in the geodatagov extension](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/templates/source/geodatagov_source_form.html#L53).

`data.private_datasets` doesn't exist. Here are the kv pairs under `data`.

![image](https://user-images.githubusercontent.com/38019872/92502908-bbcb5780-f1bd-11ea-8c51-86f76f2a735b.png)

Changing to `data.private` seems to work locally. Not sure if we want to implement this change as I'm not certain how this would affect catalog-next.

**Comment by jbrown-xentity** [comment]
I think the private/public functionality of a harvest source comes from the geodatagov extension itself, so it should be safe to change the code to the appropriate variable... I say go for the fix and we'll figure out with the CKAN-multi team if the fix breaks something on their end.

**Comment by pjsharpe07** [comment]
It looks like the `selected` isn't populating in catalog classic:

![image](https://user-images.githubusercontent.com/38019872/92953278-b15bc880-f41e-11ea-8569-b43980ac0cbb.png)


but is populating in catalog-next:
![image](https://user-images.githubusercontent.com/38019872/92953322-c0db1180-f41e-11ea-81b5-8452befa2d9b.png)

**Comment by pjsharpe07** [comment]
Marking as `Done` as this is fixed in catalog-next

**Comment by mogul** [comment]
Moving to `Icebox` until the epic for catalog-next lands... Will close this once the problem is fixed in production!

**Comment by pjsharpe07** [comment]
If a logged in admin user edits a public harvest source the `dataset visibility` drop down will retain the `public` property instead of defaulting to `private` automatically. See [doi-open-data](https://catalog.data.gov/harvest/doi-open-data) for an example.

**Comment by FuhuXia** [comment]
Still an issue, confirmed on any harvest type of `Web Accessible Folder (WAF) Homogeneous Collection`, such as [this one](https://admin-catalog-next.data.gov/harvest/edit/current-tabblock20).

**Comment by mogul** [comment]
As this is a regression, we want to be sure to add a test as we fix this.

**Comment by jbrown-xentity** [comment]
Confirmed working on production, and test case covers for cloud.gov environment!
